import type { Envio, Malote, Setor } from "./models";

// Carga inicial extraída de CONTROLE MENSAGERIA 1(2).xlsx.
// Os registros são gravados uma única vez no IndexedDB deste dispositivo.
export const MENSAGERIA_SECTORS = [
  {
    "id": "juridico",
    "nome": "JURIDICO",
    "responsavel": "JURIDICO CORP - BR, JOYCE CRUZ E LUANA BOLZAN"
  },
  {
    "id": "multas",
    "nome": "MULTAS",
    "responsavel": "EDUARDA LOIOLA ARRUDA"
  },
  {
    "id": "doacoes",
    "nome": "DOACOES",
    "responsavel": "RH"
  },
  {
    "id": "logistica",
    "nome": "LOGISTICA",
    "responsavel": "LARISSA TORETA E TIME"
  },
  {
    "id": "compras",
    "nome": "COMPRAS",
    "responsavel": "RODRIGO COSTA RODRIGUES"
  },
  {
    "id": "telefonia",
    "nome": "CONTAS TELEFONIA",
    "responsavel": "OSMAN"
  },
  {
    "id": "financas",
    "nome": "FINANCAS - CREDITOS",
    "responsavel": "ANDERSON CABRAL, EDINALDO SANTANA E RONALDO SOUSA"
  },
  {
    "id": "serasa",
    "nome": "SERASA E PROTESTO",
    "responsavel": "LOCAL BR"
  },
  {
    "id": "fretes",
    "nome": "PAGAMENTOS DE FRETES/FEDEX CORREIOS",
    "responsavel": "EDUARDA LOIOLA ARRUDA / FACILITIES"
  },
  {
    "id": "nao-classificado",
    "nome": "NÃO CLASSIFICADO",
    "responsavel": "A definir"
  }
] satisfies Setor[];

export const INITIAL_MALOTES = [
  {
    "id": "planilha-entrega-2",
    "remetente": "EDK MINERACAO",
    "destinatario": "RONALDO CARRASCO",
    "codigo_rastreio": "OY62398799BR",
    "codigo_interno": "SW-25062601",
    "item_descricao": "1 CX",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-06-25T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:2",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 2,
    "created_at": "2026-06-25T12:00:00.000Z",
    "updated_at": "2026-06-25T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-3",
    "remetente": "ONDEMAND",
    "destinatario": "SODEXO",
    "codigo_rastreio": "AD554224623BR",
    "codigo_interno": "SW-29062601",
    "item_descricao": "1 CX",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-06-29T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:3",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 3,
    "created_at": "2026-06-29T12:00:00.000Z",
    "updated_at": "2026-06-29T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-4",
    "remetente": "OMEGA",
    "destinatario": "SODEXO",
    "codigo_rastreio": "AD558413208BR",
    "codigo_interno": "SW-29062602",
    "item_descricao": "1 CX",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-06-29T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:4",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 4,
    "created_at": "2026-06-29T12:00:00.000Z",
    "updated_at": "2026-06-29T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-5",
    "remetente": "OMEGA",
    "destinatario": "SODEXO",
    "codigo_rastreio": "AD530828275BR",
    "codigo_interno": "SW-29062603",
    "item_descricao": "1 CX",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-06-29T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:5",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 5,
    "created_at": "2026-06-29T12:00:00.000Z",
    "updated_at": "2026-06-29T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-6",
    "remetente": "OMEGA",
    "destinatario": "SODEXO",
    "codigo_rastreio": "AD537036320BR",
    "codigo_interno": "SW-29062604",
    "item_descricao": "1 CX",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-06-29T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:6",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 6,
    "created_at": "2026-06-29T12:00:00.000Z",
    "updated_at": "2026-06-29T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-7",
    "remetente": "EDK MINERACAO",
    "destinatario": "RONALDO CARRASCO",
    "codigo_rastreio": "OY762399278BR",
    "codigo_interno": "SW-25062602",
    "item_descricao": "1 CX",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-06-25T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:7",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 7,
    "created_at": "2026-06-25T12:00:00.000Z",
    "updated_at": "2026-06-25T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-8",
    "remetente": "FILM3 DIGITAL",
    "destinatario": "JULIA PAGLERANI",
    "codigo_rastreio": "OY607167267BR",
    "codigo_interno": null,
    "item_descricao": "1 CX",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": null,
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:8",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 8,
    "created_at": "2026-08-31T12:00:00.000Z",
    "updated_at": "2026-08-31T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-9",
    "remetente": "PODER JUDICIARIO",
    "destinatario": "SUVINIL",
    "codigo_rastreio": "BN408415367BR",
    "codigo_interno": "SW-29062605",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-06-29T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR ANA CAROLINA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:9",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 9,
    "created_at": "2026-06-29T12:00:00.000Z",
    "updated_at": "2026-06-29T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-10",
    "remetente": "CCDEC - SUCOM",
    "destinatario": "SUVINIL",
    "codigo_rastreio": "YO094338483BR",
    "codigo_interno": "SW-29062606",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-06-29T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR ANA CAROLINA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:10",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 10,
    "created_at": "2026-06-29T12:00:00.000Z",
    "updated_at": "2026-06-29T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-11",
    "remetente": "OFFICE TEC",
    "destinatario": "SODEXO",
    "codigo_rastreio": "OY780448908BR",
    "codigo_interno": "SW-29062607",
    "item_descricao": "1 CX",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-06-29T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:11",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 11,
    "created_at": "2026-06-29T12:00:00.000Z",
    "updated_at": "2026-06-29T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-12",
    "remetente": "EMERSON SILVA - MORUMBI",
    "destinatario": "JULIANA FERREIRA DA SILVA",
    "codigo_rastreio": "235310",
    "codigo_interno": "SW-26062601",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-06-26T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:12",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 12,
    "created_at": "2026-06-26T12:00:00.000Z",
    "updated_at": "2026-06-26T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-13",
    "remetente": "VARPE BRASIL",
    "destinatario": "SUVINIL - GERVANO",
    "codigo_rastreio": "AD611121434BR",
    "codigo_interno": "SW-01072601",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-01T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:13",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 13,
    "created_at": "2026-07-01T12:00:00.000Z",
    "updated_at": "2026-07-01T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-14",
    "remetente": "TOMBINI E CIA",
    "destinatario": "SUVINIL - P3",
    "codigo_rastreio": "AD606579876BR",
    "codigo_interno": "SW-01072602",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-01T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:14",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 14,
    "created_at": "2026-07-01T12:00:00.000Z",
    "updated_at": "2026-07-01T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-15",
    "remetente": "BANCO CITIBANK",
    "destinatario": "SUVINIL",
    "codigo_rastreio": "BN570921512BR",
    "codigo_interno": "RECEBIDO POR GLEICE",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": null,
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO NO EMAIL 20/07",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:15",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 15,
    "created_at": "2026-08-31T12:00:00.000Z",
    "updated_at": "2026-08-31T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-16",
    "remetente": "BANCO CITIBANK",
    "destinatario": "SUVINIL",
    "codigo_rastreio": "BN570921702BR",
    "codigo_interno": "RECEBIDO POR GLEICE",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": null,
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO NO EMAIL 20/07",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:16",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 16,
    "created_at": "2026-08-31T12:00:00.000Z",
    "updated_at": "2026-08-31T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-17",
    "remetente": "BANCO CITIBANK",
    "destinatario": "SUVINIL",
    "codigo_rastreio": "BN570921852BR",
    "codigo_interno": "RECEBIDO POR GLEICE",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": null,
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO NO EMAIL 20/07",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:17",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 17,
    "created_at": "2026-08-31T12:00:00.000Z",
    "updated_at": "2026-08-31T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-18",
    "remetente": "SUATV",
    "destinatario": "SUVINIL - CAROLINE CARPANEZ - A220",
    "codigo_rastreio": "OY704453425BR",
    "codigo_interno": "SW-02072601",
    "item_descricao": "1 CX",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-02T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:18",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 18,
    "created_at": "2026-07-02T12:00:00.000Z",
    "updated_at": "2026-07-02T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-19",
    "remetente": "BASF SAO FRANCISCO",
    "destinatario": "SUVINIL - CAMILA A160",
    "codigo_rastreio": "AD630013928BR",
    "codigo_interno": "SW-02072602",
    "item_descricao": "1 CX",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-02T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "FINALIZADO POR TALITA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:19",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 19,
    "created_at": "2026-07-02T12:00:00.000Z",
    "updated_at": "2026-07-02T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-20",
    "remetente": "SARA CRISTINA - SHERWIN",
    "destinatario": "SARA ROJO - SHERWIN MORUMBI",
    "codigo_rastreio": null,
    "codigo_interno": "SW-13072601",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-13T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "RECEBIDO NA P1",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:20",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 20,
    "created_at": "2026-07-13T12:00:00.000Z",
    "updated_at": "2026-07-13T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-21",
    "remetente": "PREFEITURA DE MAUA",
    "destinatario": "ROBERTO YUJI NISHITAN - SHERWIN",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072601",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "aguardando_entrega",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "DEVOLUCAO",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:21",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 21,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-22",
    "remetente": "DEP ESTRADAS DE RODAGEM",
    "destinatario": "BASF SA - MULTA",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072602",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "MULTAS",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "aguardando_entrega",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "RH",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:22",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 22,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-23",
    "remetente": "VIVO",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072603",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "CONTAS TELEFONIA",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "OSMAN",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:23",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 23,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-24",
    "remetente": "VIVO",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072604",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "CONTAS TELEFONIA",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "OSMAN",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:24",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 24,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-25",
    "remetente": "FEDEX",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072605",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "PAGAMENTOS DE FRETES/FEDEX CORREIOS",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "aguardando_entrega",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:25",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 25,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-26",
    "remetente": "BANCO DAYCOVAL",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072606",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "FINANCAS - CREDITOS",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO VIA EMAIL PARA FINANCEIRO",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:26",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 26,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-27",
    "remetente": "BANCO DAYCOVAL",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072607",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "FINANCAS - CREDITOS",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO VIA EMAIL PARA FINANCEIRO",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:27",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 27,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-28",
    "remetente": "SERASA",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072608",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "FINANCAS - CREDITOS",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO VIA EMAIL PARA FINANCEIRO",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:28",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 28,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-29",
    "remetente": "SERASA",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072609",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "FINANCAS - CREDITOS",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO VIA EMAIL PARA FINANCEIRO",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:29",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 29,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-30",
    "remetente": "SERASA",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072610",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "FINANCAS - CREDITOS",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO VIA EMAIL PARA FINANCEIRO",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:30",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 30,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-31",
    "remetente": "ANTT",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072611",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO VIA EMAIL",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:31",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 31,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-32",
    "remetente": "BRADESCO",
    "destinatario": "VALCIR JOSE",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072612",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "aguardando_entrega",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "RH",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:32",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 32,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-33",
    "remetente": "FUNDACAO ANDRE TOSSELO",
    "destinatario": "BASF SA - DEPTO COMPRAS",
    "codigo_rastreio": "PB204109",
    "codigo_interno": "SW-14072613",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "COMPRAS",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE PARA RODRIGO",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:33",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 33,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-34",
    "remetente": "GH SOLUCIONADOR LOGISTICO",
    "destinatario": "BASF SA",
    "codigo_rastreio": "OY644611988BR",
    "codigo_interno": "SW-14072614",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "LOGISTICA",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "LARISSA TORETA - C340",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:34",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 34,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-35",
    "remetente": "TOMBINI E CIA",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": "AD655714847BR",
    "codigo_interno": "SW-14072615",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "LARISSA TORETA - C340",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:35",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 35,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-36",
    "remetente": "SCHWEITZER LABORATORIES",
    "destinatario": "JOSE ROBERTO - BASF S.A",
    "codigo_rastreio": "PB205035",
    "codigo_interno": "SW-14072616",
    "item_descricao": "REVISTA",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIAR VIA MALOTE PARA O MORUMBI",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:36",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 36,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-37",
    "remetente": "EDITORA PONTO DE VISTA SIRIUS",
    "destinatario": "PRISCILA CAMARA LEAL",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072617",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIAR VIA MALOTE PARA O MORUMBI",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:37",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 37,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-38",
    "remetente": "EDITORA PONTO DE VISTA SIRIUS",
    "destinatario": "CLEITON BARBOSA LUNA",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072618",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIAR VIA MALOTE PARA O MORUMBI",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:38",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 38,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-39",
    "remetente": "EDK MINERACAO",
    "destinatario": "RONALDO CARRASCO - SUVINIL",
    "codigo_rastreio": "OY762399851BR",
    "codigo_interno": "SW-14072619",
    "item_descricao": "1 CX",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE PARA ALINE",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:39",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 39,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-40",
    "remetente": "SIMPRESS",
    "destinatario": "RAFAEL - T.I",
    "codigo_rastreio": null,
    "codigo_interno": "SW-14072620",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "aguardando_entrega",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:40",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 40,
    "created_at": "2026-07-14T12:00:00.000Z",
    "updated_at": "2026-07-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-41",
    "remetente": "GRI GERENCIAMENTO",
    "destinatario": "ISABELLE MARQUES",
    "codigo_rastreio": "OY831801480BR",
    "codigo_interno": "SW-15072601",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-15T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE PARA ISABELLE",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:41",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 41,
    "created_at": "2026-07-15T12:00:00.000Z",
    "updated_at": "2026-07-15T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-42",
    "remetente": "TOMBINI E CIA",
    "destinatario": "LARISSA TORETA - C140",
    "codigo_rastreio": null,
    "codigo_interno": "SW-15072602",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-15T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE NA P3 - DAVID",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:42",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 42,
    "created_at": "2026-07-15T12:00:00.000Z",
    "updated_at": "2026-07-15T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-43",
    "remetente": "GRUPO MRS",
    "destinatario": "NARCILIO BATISTA",
    "codigo_rastreio": "YH223158121BR",
    "codigo_interno": "SW-15072603",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-15T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO VIA EMAIL 20/07",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:43",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 43,
    "created_at": "2026-07-15T12:00:00.000Z",
    "updated_at": "2026-07-15T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-44",
    "remetente": "CORREIOS",
    "destinatario": "SUVINIL",
    "codigo_rastreio": "BF143678392BR",
    "codigo_interno": "SW-15072604",
    "item_descricao": "ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "PAGAMENTOS DE FRETES/FEDEX CORREIOS",
    "recebido_em": "2026-07-15T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "aguardando_entrega",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:44",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 44,
    "created_at": "2026-07-15T12:00:00.000Z",
    "updated_at": "2026-07-15T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-45",
    "remetente": "SIMPRESS",
    "destinatario": "RAFAEL ARAUJO - T.I",
    "codigo_rastreio": null,
    "codigo_interno": "SW-16072601",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-16T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "aguardando_entrega",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:45",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 45,
    "created_at": "2026-07-16T12:00:00.000Z",
    "updated_at": "2026-07-16T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-46",
    "remetente": "RN TINTAS E FERRAMENTAS",
    "destinatario": "PREDIO A160 - SAMUEL ASSIS",
    "codigo_rastreio": "OY806189540BR",
    "codigo_interno": "SW-16072602",
    "item_descricao": "1 CAIXA",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-16T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "aguardando_entrega",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:46",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 46,
    "created_at": "2026-07-16T12:00:00.000Z",
    "updated_at": "2026-07-16T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-47",
    "remetente": "CONECT COMERCIAL",
    "destinatario": "SUVINIL COATINGS - GABRIELA BRITO",
    "codigo_rastreio": "OY726149034BR",
    "codigo_interno": "SW-16072603",
    "item_descricao": "1 CAIXA",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-16T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE PARA GABRIELA BRITO",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:47",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 47,
    "created_at": "2026-07-16T12:00:00.000Z",
    "updated_at": "2026-07-16T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-48",
    "remetente": "ONDEMAND",
    "destinatario": "SODEXO",
    "codigo_rastreio": "AD681866749BR",
    "codigo_interno": "SW-16072604",
    "item_descricao": "1 PACOTE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-16T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:48",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 48,
    "created_at": "2026-07-16T12:00:00.000Z",
    "updated_at": "2026-07-16T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-49",
    "remetente": "MANTRIS GESTAO EM SAUDE",
    "destinatario": "SUVINIL COATINGS - MEDICINA",
    "codigo_rastreio": "AD680578922BR",
    "codigo_interno": "SW-16072605",
    "item_descricao": "1 PACOTE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-16T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:49",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 49,
    "created_at": "2026-07-16T12:00:00.000Z",
    "updated_at": "2026-07-16T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-50",
    "remetente": "EMERSON SILVA - MORUMBI",
    "destinatario": "ESTEVAM / BEATRIZ",
    "codigo_rastreio": null,
    "codigo_interno": null,
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-17T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:50",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 50,
    "created_at": "2026-07-17T12:00:00.000Z",
    "updated_at": "2026-07-17T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-51",
    "remetente": "EMERSON SILVA - MORUMBI",
    "destinatario": "JEFERSON / HUGO",
    "codigo_rastreio": null,
    "codigo_interno": null,
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-17T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:51",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 51,
    "created_at": "2026-07-17T12:00:00.000Z",
    "updated_at": "2026-07-17T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-52",
    "remetente": "CITIBANK",
    "destinatario": "SUVINIL COATINGS - TATIANE ROCHA",
    "codigo_rastreio": "BN570922795BR",
    "codigo_interno": null,
    "item_descricao": "1 ENVELOPE",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-17T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO NO EMAIL DIA 20/07",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:52",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 52,
    "created_at": "2026-07-17T12:00:00.000Z",
    "updated_at": "2026-07-17T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-53",
    "remetente": "6 TABELIAO DE PROTESTO",
    "destinatario": "BASF SA",
    "codigo_rastreio": "PB2019522845F0",
    "codigo_interno": "SW-17072601",
    "item_descricao": "ENVIADO NO EMAIL 24/07",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "SERASA E PROTESTO",
    "recebido_em": "2026-07-17T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO NO EMAIL DIA 20/07",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:53",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 53,
    "created_at": "2026-07-17T12:00:00.000Z",
    "updated_at": "2026-07-17T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-54",
    "remetente": "REINALDO / MARRESE",
    "destinatario": "RODRIGO ASSIS - GPS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-20072601",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-20T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "1 CHAVE",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:54",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 54,
    "created_at": "2026-07-20T12:00:00.000Z",
    "updated_at": "2026-07-20T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-55",
    "remetente": "REINALDO / MARRESE",
    "destinatario": "RODRIGO ASSIS - GPS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-20072602",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-20T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "1 ALICATE AMPERIMETRO",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:55",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 55,
    "created_at": "2026-07-20T12:00:00.000Z",
    "updated_at": "2026-07-20T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-56",
    "remetente": "VIVO",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-17072602",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "CONTAS TELEFONIA",
    "recebido_em": "2026-07-17T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "10 ENVELOPES DE COBRANCA VIVO",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:56",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 56,
    "created_at": "2026-07-17T12:00:00.000Z",
    "updated_at": "2026-07-17T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-57",
    "remetente": "ECORODOVIAS",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW-17072603",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-17T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "1 ENVELOPE",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:57",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 57,
    "created_at": "2026-07-17T12:00:00.000Z",
    "updated_at": "2026-07-17T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-58",
    "remetente": "BANCO DO BRASIL",
    "destinatario": "BASF S/A",
    "codigo_rastreio": null,
    "codigo_interno": "SW-17072604",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-17T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "1 ENVELOPE",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:58",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 58,
    "created_at": "2026-07-17T12:00:00.000Z",
    "updated_at": "2026-07-17T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-59",
    "remetente": "DEBITOS / COBRANCA",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW17072605",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "FINANCAS - CREDITOS",
    "recebido_em": "2026-07-17T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "15 ENVELOPES - ENVIADOS DIA 20/07",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:59",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 59,
    "created_at": "2026-07-17T12:00:00.000Z",
    "updated_at": "2026-07-17T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-60",
    "remetente": "LABORATORIO",
    "destinatario": "RICARDO CARRIEL - QSMS",
    "codigo_rastreio": "OY812581857BR",
    "codigo_interno": "SW27072601",
    "item_descricao": "1 CAIXA",
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-07-27T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE 27/07/2026",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:60",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 60,
    "created_at": "2026-07-27T12:00:00.000Z",
    "updated_at": "2026-07-27T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-61",
    "remetente": "EXAMES",
    "destinatario": "MEDICINA DO TRABALHO",
    "codigo_rastreio": null,
    "codigo_interno": "SW12082601",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-08-12T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE DIA 13/08",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:61",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 61,
    "created_at": "2026-08-12T12:00:00.000Z",
    "updated_at": "2026-08-12T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-62",
    "remetente": "SERVICO PUB FEDERAL",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": null,
    "codigo_interno": "SW12082602",
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-08-12T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENVIADO NO EMAIL DIA 13/08",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:62",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 62,
    "created_at": "2026-08-12T12:00:00.000Z",
    "updated_at": "2026-08-12T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-63",
    "remetente": "SIMPRESS",
    "destinatario": "RAFAEL T.I",
    "codigo_rastreio": null,
    "codigo_interno": null,
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-08-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE DIA 14/08",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:63",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 63,
    "created_at": "2026-08-14T12:00:00.000Z",
    "updated_at": "2026-08-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-64",
    "remetente": "MORUMBI",
    "destinatario": "SUVINIL",
    "codigo_rastreio": null,
    "codigo_interno": null,
    "item_descricao": null,
    "local_recebimento": "Portaria",
    "quantidade": 1,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": "2026-08-14T12:00:00.000Z",
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "ENTREGUE DIA 14/08 - HEADSETS",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:64",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 64,
    "created_at": "2026-08-14T12:00:00.000Z",
    "updated_at": "2026-08-14T12:00:00.000Z"
  },
  {
    "id": "planilha-entrega-65",
    "remetente": "SIMPRESS",
    "destinatario": "RAFAEL T.I",
    "codigo_rastreio": null,
    "codigo_interno": null,
    "item_descricao": "4 CAIXAS",
    "local_recebimento": "Portaria",
    "quantidade": 4,
    "setor": "NÃO CLASSIFICADO",
    "recebido_em": null,
    "recebido_por": "Não registrado no legado",
    "assinatura_portaria_data_url": null,
    "observacoes": null,
    "status": "entregue",
    "entregue_em": null,
    "entregue_para": null,
    "assinatura_entrega_data_url": null,
    "entrega_observacoes": "4 CAIXAS ENTREGUES DIA 26/08",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/ENTREGA:65",
    "legacy_source": "CONTROLE MENSAGERIA/ENTREGA",
    "legacy_source_row": 65,
    "created_at": "2026-08-31T12:00:00.000Z",
    "updated_at": "2026-08-31T12:00:00.000Z"
  }
] satisfies Malote[];

export const INITIAL_ENVIOS = [
  {
    "id": "planilha-envio-correios-2",
    "categoria": "correios",
    "remetente": "SUVINIL - RH",
    "destinatario": "JABOATAO",
    "codigo_rastreio": "OY880576856BR",
    "item_descricao": "2 CRACHAS",
    "nota_fiscal": null,
    "enviado_em": null,
    "enviado_por": null,
    "status": "finalizado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/CORREIOS:2",
    "legacy_source": "CONTROLE MENSAGERIA/CORREIOS",
    "legacy_source_row": 2,
    "created_at": "2026-08-31T12:00:00.000Z",
    "updated_at": "2026-08-31T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-correios-3",
    "categoria": "correios",
    "remetente": "RAFAEL ARAUJO",
    "destinatario": "JABOATAO",
    "codigo_rastreio": "OY880578168BR",
    "item_descricao": "1 CAIXA PORTE MEDIO",
    "nota_fiscal": null,
    "enviado_em": "2026-07-01T12:00:00.000Z",
    "enviado_por": null,
    "status": "finalizado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/CORREIOS:3",
    "legacy_source": "CONTROLE MENSAGERIA/CORREIOS",
    "legacy_source_row": 3,
    "created_at": "2026-07-01T12:00:00.000Z",
    "updated_at": "2026-07-01T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-correios-4",
    "categoria": "correios",
    "remetente": "SHERWIN - RAFAEL FEITOSA",
    "destinatario": "JABOATAO - JULIA GABRIELA",
    "codigo_rastreio": "OY986401440BR",
    "item_descricao": "1 CAIXA 70CM",
    "nota_fiscal": null,
    "enviado_em": "2026-07-03T12:00:00.000Z",
    "enviado_por": null,
    "status": "finalizado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/CORREIOS:4",
    "legacy_source": "CONTROLE MENSAGERIA/CORREIOS",
    "legacy_source_row": 4,
    "created_at": "2026-07-03T12:00:00.000Z",
    "updated_at": "2026-07-03T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-correios-5",
    "categoria": "correios",
    "remetente": "ALINE GUTIERRI",
    "destinatario": "YMERIS DAVID BROBOW",
    "codigo_rastreio": "OY986427481BR",
    "item_descricao": "3 CAIXAS",
    "nota_fiscal": "284",
    "enviado_em": "2026-07-22T12:00:00.000Z",
    "enviado_por": null,
    "status": "finalizado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/CORREIOS:5",
    "legacy_source": "CONTROLE MENSAGERIA/CORREIOS",
    "legacy_source_row": 5,
    "created_at": "2026-07-22T12:00:00.000Z",
    "updated_at": "2026-07-22T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-correios-6",
    "categoria": "correios",
    "remetente": "ALINE GUTIERRI",
    "destinatario": "SELAFORT",
    "codigo_rastreio": "OY986427495BR",
    "item_descricao": "3CAIXAS",
    "nota_fiscal": "285",
    "enviado_em": "2026-07-22T12:00:00.000Z",
    "enviado_por": null,
    "status": "finalizado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/CORREIOS:6",
    "legacy_source": "CONTROLE MENSAGERIA/CORREIOS",
    "legacy_source_row": 6,
    "created_at": "2026-07-22T12:00:00.000Z",
    "updated_at": "2026-07-22T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-correios-7",
    "categoria": "correios",
    "remetente": "ALINE GUTIERRI",
    "destinatario": "YMERIS DAVID BROBOW",
    "codigo_rastreio": "OY986427504BR",
    "item_descricao": "1 CAIXA",
    "nota_fiscal": null,
    "enviado_em": "2026-07-08T12:00:00.000Z",
    "enviado_por": null,
    "status": "finalizado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/CORREIOS:7",
    "legacy_source": "CONTROLE MENSAGERIA/CORREIOS",
    "legacy_source_row": 7,
    "created_at": "2026-07-08T12:00:00.000Z",
    "updated_at": "2026-07-08T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-correios-8",
    "categoria": "correios",
    "remetente": "ALINE GUTIERRI",
    "destinatario": "SELAFORT",
    "codigo_rastreio": "OY986427518BR",
    "item_descricao": "1 CAIXA",
    "nota_fiscal": null,
    "enviado_em": "2026-07-08T12:00:00.000Z",
    "enviado_por": null,
    "status": "finalizado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/CORREIOS:8",
    "legacy_source": "CONTROLE MENSAGERIA/CORREIOS",
    "legacy_source_row": 8,
    "created_at": "2026-07-08T12:00:00.000Z",
    "updated_at": "2026-07-08T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-correios-9",
    "categoria": "correios",
    "remetente": "ALINE GUTIERRI",
    "destinatario": "YMERIS DAVID BROBOW",
    "codigo_rastreio": "OY986427521BR",
    "item_descricao": "1 CAIXA",
    "nota_fiscal": null,
    "enviado_em": "2026-07-08T12:00:00.000Z",
    "enviado_por": null,
    "status": "finalizado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/CORREIOS:9",
    "legacy_source": "CONTROLE MENSAGERIA/CORREIOS",
    "legacy_source_row": 9,
    "created_at": "2026-07-08T12:00:00.000Z",
    "updated_at": "2026-07-08T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-correios-10",
    "categoria": "correios",
    "remetente": "ALINE GUTIERRI",
    "destinatario": "SELAFORT",
    "codigo_rastreio": "OY986427535BR",
    "item_descricao": "1 CAIXA",
    "nota_fiscal": null,
    "enviado_em": "2026-07-08T12:00:00.000Z",
    "enviado_por": null,
    "status": "finalizado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/CORREIOS:10",
    "legacy_source": "CONTROLE MENSAGERIA/CORREIOS",
    "legacy_source_row": 10,
    "created_at": "2026-07-08T12:00:00.000Z",
    "updated_at": "2026-07-08T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-juridico-2",
    "categoria": "juridico",
    "remetente": "PREFEITURA DE TIMBO",
    "destinatario": "SUVINIL",
    "codigo_rastreio": "YO094647272BR",
    "item_descricao": null,
    "nota_fiscal": null,
    "enviado_em": "2026-07-01T12:00:00.000Z",
    "enviado_por": null,
    "status": "enviado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/JURIDICOS:2",
    "legacy_source": "CONTROLE MENSAGERIA/JURIDICOS",
    "legacy_source_row": 2,
    "created_at": "2026-07-01T12:00:00.000Z",
    "updated_at": "2026-07-01T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-juridico-3",
    "categoria": "juridico",
    "remetente": "SYNADEL PINTURAS",
    "destinatario": "JURIDICO",
    "codigo_rastreio": "BN576362309BR",
    "item_descricao": null,
    "nota_fiscal": null,
    "enviado_em": "2026-07-15T12:00:00.000Z",
    "enviado_por": null,
    "status": "enviado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/JURIDICOS:3",
    "legacy_source": "CONTROLE MENSAGERIA/JURIDICOS",
    "legacy_source_row": 3,
    "created_at": "2026-07-15T12:00:00.000Z",
    "updated_at": "2026-07-15T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-juridico-4",
    "categoria": "juridico",
    "remetente": "PODER JUDICIARIO",
    "destinatario": "SUVINIL",
    "codigo_rastreio": "BN408415367BR",
    "item_descricao": null,
    "nota_fiscal": null,
    "enviado_em": null,
    "enviado_por": null,
    "status": "enviado",
    "finalizado_em": null,
    "observacoes": "Valor original da data: POR ANA CAROLINE ROCHA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/JURIDICOS:4",
    "legacy_source": "CONTROLE MENSAGERIA/JURIDICOS",
    "legacy_source_row": 4,
    "created_at": "2026-08-31T12:00:00.000Z",
    "updated_at": "2026-08-31T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-juridico-5",
    "categoria": "juridico",
    "remetente": "CCDEC - SUCOM",
    "destinatario": "SUVINIL",
    "codigo_rastreio": "YO094338483BR",
    "item_descricao": null,
    "nota_fiscal": null,
    "enviado_em": null,
    "enviado_por": null,
    "status": "enviado",
    "finalizado_em": null,
    "observacoes": "Valor original da data: POR ANA CAROLINE ROCHA",
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/JURIDICOS:5",
    "legacy_source": "CONTROLE MENSAGERIA/JURIDICOS",
    "legacy_source_row": 5,
    "created_at": "2026-08-31T12:00:00.000Z",
    "updated_at": "2026-08-31T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-juridico-6",
    "categoria": "juridico",
    "remetente": "TRIBUNAL DE JUSTICA SP",
    "destinatario": "WAGNER BARBOSA TEIX",
    "codigo_rastreio": "BV844568891BR",
    "item_descricao": null,
    "nota_fiscal": null,
    "enviado_em": "2026-07-23T12:00:00.000Z",
    "enviado_por": null,
    "status": "enviado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/JURIDICOS:6",
    "legacy_source": "CONTROLE MENSAGERIA/JURIDICOS",
    "legacy_source_row": 6,
    "created_at": "2026-07-23T12:00:00.000Z",
    "updated_at": "2026-07-23T12:00:00.000Z"
  },
  {
    "id": "planilha-envio-juridico-7",
    "categoria": "juridico",
    "remetente": "MACEDO CARBONELLI",
    "destinatario": "SUVINIL COATINGS",
    "codigo_rastreio": "OY631330723BR",
    "item_descricao": null,
    "nota_fiscal": null,
    "enviado_em": "2026-07-29T12:00:00.000Z",
    "enviado_por": null,
    "status": "enviado",
    "finalizado_em": null,
    "observacoes": null,
    "legacy_import": true,
    "source_key": "CONTROLE MENSAGERIA/JURIDICOS:7",
    "legacy_source": "CONTROLE MENSAGERIA/JURIDICOS",
    "legacy_source_row": 7,
    "created_at": "2026-07-29T12:00:00.000Z",
    "updated_at": "2026-07-29T12:00:00.000Z"
  }
] satisfies Envio[];

