from pathlib import Path

path = Path('src/lib/legal-items.ts')
text = path.read_text()
anchor = 'import { supabase } from "@/integrations/supabase/client";\n'
helper = anchor + '''\nconst LEGAL_AUTH_RETRY_RE = /(jwt|token|auth|session|401|403|not authenticated|failed to fetch|network)/i;\n\nfunction legalErrorMessage(error: unknown) {\n  if (error instanceof Error) return error.message;\n  if (error && typeof error === "object" && "message" in error) return String((error as { message?: unknown }).message ?? "");\n  return String(error ?? "");\n}\n\nasync function ensureLegalSession() {\n  const { data, error } = await supabase.auth.getSession();\n  if (error) throw error;\n  if (!data.session?.user) throw new Error("Sessão expirada. Entre novamente para carregar o Painel Legal.");\n}\n\nasync function withLegalReadRetry<T>(read: () => Promise<T>): Promise<T> {\n  await ensureLegalSession();\n  try {\n    return await read();\n  } catch (error) {\n    const message = legalErrorMessage(error);\n    const retryable = error instanceof TypeError || LEGAL_AUTH_RETRY_RE.test(message);\n    if (!retryable) throw error;\n    const { error: refreshError } = await supabase.auth.refreshSession();\n    if (refreshError) throw error;\n    return await read();\n  }\n}\n'''
if 'withLegalReadRetry' not in text:
    text = text.replace(anchor, helper, 1)

blocks = [
('''export async function listLegalItems(): Promise<LegalItem[]> {\n  const { data, error } = await supabase\n    .from("legal_items" as any)\n    .select("*")\n    .order("proxima_execucao", { ascending: true });\n  if (error) throw error;\n  return (data as unknown as Row[]).map(fromRow);\n}\n''', '''export async function listLegalItems(): Promise<LegalItem[]> {\n  return withLegalReadRetry(async () => {\n    const { data, error } = await supabase\n      .from("legal_items" as any)\n      .select("*")\n      .order("proxima_execucao", { ascending: true });\n    if (error) throw error;\n    return ((data as unknown as Row[]) ?? []).map(fromRow);\n  });\n}\n'''),
('''export async function listExecutions(): Promise<LegalExecution[]> {\n  const { data, error } = await supabase\n    .from("legal_item_executions" as any)\n    .select("id, item_id, data_execucao, observacao");\n  if (error) throw error;\n  return (\n    data as unknown as Array<{\n      id: string;\n      item_id: string;\n      data_execucao: string;\n      observacao: string | null;\n    }>\n  ).map((r) => ({\n    id: r.id,\n    itemId: r.item_id,\n    data: r.data_execucao,\n    observacao: r.observacao,\n  }));\n}\n''', '''export async function listExecutions(): Promise<LegalExecution[]> {\n  return withLegalReadRetry(async () => {\n    const { data, error } = await supabase\n      .from("legal_item_executions" as any)\n      .select("id, item_id, data_execucao, observacao");\n    if (error) throw error;\n    return (\n      (data as unknown as Array<{\n        id: string;\n        item_id: string;\n        data_execucao: string;\n        observacao: string | null;\n      }>) ?? []\n    ).map((r) => ({\n      id: r.id,\n      itemId: r.item_id,\n      data: r.data_execucao,\n      observacao: r.observacao,\n    }));\n  });\n}\n'''),
('''export async function listAttachments(itemId: string): Promise<LegalAttachment[]> {\n  const { data, error } = await supabase\n    .from("legal_item_attachments" as any)\n    .select("*")\n    .eq("item_id", itemId)\n    .order("is_current", { ascending: false })\n    .order("created_at", { ascending: false });\n  if (error) throw error;\n  return ((data as unknown as AttachmentRow[]) ?? []).map(fromAttachmentRow);\n}\n''', '''export async function listAttachments(itemId: string): Promise<LegalAttachment[]> {\n  return withLegalReadRetry(async () => {\n    const { data, error } = await supabase\n      .from("legal_item_attachments" as any)\n      .select("*")\n      .eq("item_id", itemId)\n      .order("is_current", { ascending: false })\n      .order("created_at", { ascending: false });\n    if (error) throw error;\n    return ((data as unknown as AttachmentRow[]) ?? []).map(fromAttachmentRow);\n  });\n}\n'''),
('''export async function countAttachments(): Promise<Record<string, number>> {\n  const { data, error } = await supabase.from("legal_item_attachments" as any).select("item_id");\n  if (error) throw error;\n  const map: Record<string, number> = {};\n  for (const row of (data as unknown as Array<{ item_id: string }>) ?? []) {\n    map[row.item_id] = (map[row.item_id] ?? 0) + 1;\n  }\n  return map;\n}\n''', '''export async function countAttachments(): Promise<Record<string, number>> {\n  return withLegalReadRetry(async () => {\n    const { data, error } = await supabase.from("legal_item_attachments" as any).select("item_id");\n    if (error) throw error;\n    const map: Record<string, number> = {};\n    for (const row of (data as unknown as Array<{ item_id: string }>) ?? []) {\n      map[row.item_id] = (map[row.item_id] ?? 0) + 1;\n    }\n    return map;\n  });\n}\n'''),
('''export async function signedUrl(path: string, expiresInSec = 3600): Promise<string> {\n  const { data, error } = await supabase.storage\n    .from("legal-certificates")\n    .createSignedUrl(path, expiresInSec);\n  if (error) throw error;\n  return data.signedUrl;\n}\n''', '''export async function signedUrl(path: string, expiresInSec = 3600): Promise<string> {\n  return withLegalReadRetry(async () => {\n    const { data, error } = await supabase.storage\n      .from("legal-certificates")\n      .createSignedUrl(path, expiresInSec);\n    if (error) throw error;\n    return data.signedUrl;\n  });\n}\n''')]
for old, new in blocks:
    if old in text:
        text = text.replace(old, new, 1)
    elif new not in text:
        raise SystemExit('expected legal-items block not found')
path.write_text(text)

path = Path('src/routes/_authenticated/painel-legal.tsx')
text = path.read_text()
old = '''  const { data: items = [], isLoading } = useQuery({\n    queryKey: ["legal-items"],\n    queryFn: listLegalItems,\n  });\n  const { data: execs = [] } = useQuery({\n    queryKey: ["legal-executions"],\n    queryFn: listExecutions,\n  });\n  const { data: attCounts = {} } = useQuery({\n    queryKey: ["legal-attachments-counts"],\n    queryFn: countAttachments,\n  });\n'''
new = '''  const {\n    data: items = [],\n    isLoading,\n    isError: itemsLoadFailed,\n    error: itemsLoadError,\n    refetch: refetchItems,\n  } = useQuery({\n    queryKey: ["legal-items"],\n    queryFn: listLegalItems,\n    retry: 2,\n    refetchOnMount: "always",\n    refetchOnWindowFocus: true,\n  });\n  const { data: execs = [], refetch: refetchExecutions } = useQuery({\n    queryKey: ["legal-executions"],\n    queryFn: listExecutions,\n    retry: 2,\n    refetchOnMount: "always",\n  });\n  const { data: attCounts = {}, refetch: refetchAttachmentCounts } = useQuery({\n    queryKey: ["legal-attachments-counts"],\n    queryFn: countAttachments,\n    retry: 2,\n    refetchOnMount: "always",\n  });\n\n  const reloadLegalData = async () => {\n    const results = await Promise.allSettled([refetchItems(), refetchExecutions(), refetchAttachmentCounts()]);\n    const failed = results.some((result) => result.status === "rejected");\n    if (failed) toast.error("Ainda não foi possível sincronizar o Painel Legal.");\n    else toast.success("Painel Legal sincronizado.");\n  };\n'''
if old in text:
    text = text.replace(old, new, 1)
elif new not in text:
    raise SystemExit('panel query block not found')
body_anchor = '''      {dialogo}\n      {/* Cabeçalho de ações — mais compacto */}\n'''
error_ui = '''      {dialogo}\n      {itemsLoadFailed && (\n        <div className="mb-3 flex flex-col gap-3 rounded-xl border border-amber-500/25 bg-amber-500/[0.07] px-4 py-3 sm:flex-row sm:items-center sm:justify-between">\n          <div className="min-w-0">\n            <p className="text-sm font-semibold text-amber-200">Falha temporária ao sincronizar o Painel Legal</p>\n            <p className="mt-0.5 text-xs text-muted-foreground">\n              Os itens e certificados continuam salvos na base. Tente reconectar a leitura sem sair da página.\n              {itemsLoadError instanceof Error && itemsLoadError.message ? ` (${itemsLoadError.message})` : ""}\n            </p>\n          </div>\n          <Button size="sm" variant="outline" className="shrink-0" onClick={() => void reloadLegalData()}>\n            Recarregar dados\n          </Button>\n        </div>\n      )}\n      {/* Cabeçalho de ações — mais compacto */}\n'''
if error_ui not in text:
    text = text.replace(body_anchor, error_ui, 1)
path.write_text(text)

path = Path('src/components/legal/legal-attachments-modal.tsx')
text = path.read_text()
old = '''    queryFn: () => (item ? listAttachments(item.id) : Promise.resolve([])),\n    enabled: Boolean(item && open),\n  });\n'''
new = '''    queryFn: () => (item ? listAttachments(item.id) : Promise.resolve([])),\n    enabled: Boolean(item && open),\n    retry: 2,\n    refetchOnMount: "always",\n    refetchOnWindowFocus: true,\n  });\n'''
if old in text:
    text = text.replace(old, new, 1)
elif new not in text:
    raise SystemExit('attachment query block not found')
path.write_text(text)
