/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTaludesRouteImport } from './routes/_authenticated/taludes'
import { Route as AuthenticatedProgramacaoTaludesRouteImport } from './routes/_authenticated/programacao-taludes'
import { Route as AuthenticatedProgramacaoRouteImport } from './routes/_authenticated/programacao'
import { Route as AuthenticatedPreventivaRouteImport } from './routes/_authenticated/preventiva'
import { Route as AuthenticatedPainelLegalRouteImport } from './routes/_authenticated/painel-legal'
import { Route as AuthenticatedOutrosRouteImport } from './routes/_authenticated/outros'
import { Route as AuthenticatedLavanderiaRouteImport } from './routes/_authenticated/lavanderia'
import { Route as AuthenticatedCorretivaRouteImport } from './routes/_authenticated/corretiva'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedBackorderRouteImport } from './routes/_authenticated/backorder'
import { Route as AuthenticatedApontamentosRouteImport } from './routes/_authenticated/apontamentos'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaludesRoute = AuthenticatedTaludesRouteImport.update({
  id: '/taludes',
  path: '/taludes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramacaoTaludesRoute =
  AuthenticatedProgramacaoTaludesRouteImport.update({
    id: '/programacao-taludes',
    path: '/programacao-taludes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgramacaoRoute =
  AuthenticatedProgramacaoRouteImport.update({
    id: '/programacao',
    path: '/programacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreventivaRoute = AuthenticatedPreventivaRouteImport.update({
  id: '/preventiva',
  path: '/preventiva',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelLegalRoute =
  AuthenticatedPainelLegalRouteImport.update({
    id: '/painel-legal',
    path: '/painel-legal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutrosRoute = AuthenticatedOutrosRouteImport.update({
  id: '/outros',
  path: '/outros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLavanderiaRoute = AuthenticatedLavanderiaRouteImport.update({
  id: '/lavanderia',
  path: '/lavanderia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorretivaRoute = AuthenticatedCorretivaRouteImport.update({
  id: '/corretiva',
  path: '/corretiva',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBackorderRoute = AuthenticatedBackorderRouteImport.update({
  id: '/backorder',
  path: '/backorder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApontamentosRoute =
  AuthenticatedApontamentosRouteImport.update({
    id: '/apontamentos',
    path: '/apontamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/apontamentos': typeof AuthenticatedApontamentosRoute
  '/backorder': typeof AuthenticatedBackorderRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/corretiva': typeof AuthenticatedCorretivaRoute
  '/lavanderia': typeof AuthenticatedLavanderiaRoute
  '/outros': typeof AuthenticatedOutrosRoute
  '/painel-legal': typeof AuthenticatedPainelLegalRoute
  '/preventiva': typeof AuthenticatedPreventivaRoute
  '/programacao': typeof AuthenticatedProgramacaoRoute
  '/programacao-taludes': typeof AuthenticatedProgramacaoTaludesRoute
  '/taludes': typeof AuthenticatedTaludesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/apontamentos': typeof AuthenticatedApontamentosRoute
  '/backorder': typeof AuthenticatedBackorderRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/corretiva': typeof AuthenticatedCorretivaRoute
  '/lavanderia': typeof AuthenticatedLavanderiaRoute
  '/outros': typeof AuthenticatedOutrosRoute
  '/painel-legal': typeof AuthenticatedPainelLegalRoute
  '/preventiva': typeof AuthenticatedPreventivaRoute
  '/programacao': typeof AuthenticatedProgramacaoRoute
  '/programacao-taludes': typeof AuthenticatedProgramacaoTaludesRoute
  '/taludes': typeof AuthenticatedTaludesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/_authenticated/apontamentos': typeof AuthenticatedApontamentosRoute
  '/_authenticated/backorder': typeof AuthenticatedBackorderRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/corretiva': typeof AuthenticatedCorretivaRoute
  '/_authenticated/lavanderia': typeof AuthenticatedLavanderiaRoute
  '/_authenticated/outros': typeof AuthenticatedOutrosRoute
  '/_authenticated/painel-legal': typeof AuthenticatedPainelLegalRoute
  '/_authenticated/preventiva': typeof AuthenticatedPreventivaRoute
  '/_authenticated/programacao': typeof AuthenticatedProgramacaoRoute
  '/_authenticated/programacao-taludes': typeof AuthenticatedProgramacaoTaludesRoute
  '/_authenticated/taludes': typeof AuthenticatedTaludesRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/apontamentos'
    | '/backorder'
    | '/configuracoes'
    | '/corretiva'
    | '/lavanderia'
    | '/outros'
    | '/painel-legal'
    | '/preventiva'
    | '/programacao'
    | '/programacao-taludes'
    | '/taludes'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/contato'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/apontamentos'
    | '/backorder'
    | '/configuracoes'
    | '/corretiva'
    | '/lavanderia'
    | '/outros'
    | '/painel-legal'
    | '/preventiva'
    | '/programacao'
    | '/programacao-taludes'
    | '/taludes'
    | '/usuarios'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/_authenticated/apontamentos'
    | '/_authenticated/backorder'
    | '/_authenticated/configuracoes'
    | '/_authenticated/corretiva'
    | '/_authenticated/lavanderia'
    | '/_authenticated/outros'
    | '/_authenticated/painel-legal'
    | '/_authenticated/preventiva'
    | '/_authenticated/programacao'
    | '/_authenticated/programacao-taludes'
    | '/_authenticated/taludes'
    | '/_authenticated/usuarios'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taludes': {
      id: '/_authenticated/taludes'
      path: '/taludes'
      fullPath: '/taludes'
      preLoaderRoute: typeof AuthenticatedTaludesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programacao-taludes': {
      id: '/_authenticated/programacao-taludes'
      path: '/programacao-taludes'
      fullPath: '/programacao-taludes'
      preLoaderRoute: typeof AuthenticatedProgramacaoTaludesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programacao': {
      id: '/_authenticated/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof AuthenticatedProgramacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preventiva': {
      id: '/_authenticated/preventiva'
      path: '/preventiva'
      fullPath: '/preventiva'
      preLoaderRoute: typeof AuthenticatedPreventivaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-legal': {
      id: '/_authenticated/painel-legal'
      path: '/painel-legal'
      fullPath: '/painel-legal'
      preLoaderRoute: typeof AuthenticatedPainelLegalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outros': {
      id: '/_authenticated/outros'
      path: '/outros'
      fullPath: '/outros'
      preLoaderRoute: typeof AuthenticatedOutrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lavanderia': {
      id: '/_authenticated/lavanderia'
      path: '/lavanderia'
      fullPath: '/lavanderia'
      preLoaderRoute: typeof AuthenticatedLavanderiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corretiva': {
      id: '/_authenticated/corretiva'
      path: '/corretiva'
      fullPath: '/corretiva'
      preLoaderRoute: typeof AuthenticatedCorretivaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backorder': {
      id: '/_authenticated/backorder'
      path: '/backorder'
      fullPath: '/backorder'
      preLoaderRoute: typeof AuthenticatedBackorderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apontamentos': {
      id: '/_authenticated/apontamentos'
      path: '/apontamentos'
      fullPath: '/apontamentos'
      preLoaderRoute: typeof AuthenticatedApontamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApontamentosRoute: typeof AuthenticatedApontamentosRoute
  AuthenticatedBackorderRoute: typeof AuthenticatedBackorderRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCorretivaRoute: typeof AuthenticatedCorretivaRoute
  AuthenticatedLavanderiaRoute: typeof AuthenticatedLavanderiaRoute
  AuthenticatedOutrosRoute: typeof AuthenticatedOutrosRoute
  AuthenticatedPainelLegalRoute: typeof AuthenticatedPainelLegalRoute
  AuthenticatedPreventivaRoute: typeof AuthenticatedPreventivaRoute
  AuthenticatedProgramacaoRoute: typeof AuthenticatedProgramacaoRoute
  AuthenticatedProgramacaoTaludesRoute: typeof AuthenticatedProgramacaoTaludesRoute
  AuthenticatedTaludesRoute: typeof AuthenticatedTaludesRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApontamentosRoute: AuthenticatedApontamentosRoute,
  AuthenticatedBackorderRoute: AuthenticatedBackorderRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCorretivaRoute: AuthenticatedCorretivaRoute,
  AuthenticatedLavanderiaRoute: AuthenticatedLavanderiaRoute,
  AuthenticatedOutrosRoute: AuthenticatedOutrosRoute,
  AuthenticatedPainelLegalRoute: AuthenticatedPainelLegalRoute,
  AuthenticatedPreventivaRoute: AuthenticatedPreventivaRoute,
  AuthenticatedProgramacaoRoute: AuthenticatedProgramacaoRoute,
  AuthenticatedProgramacaoTaludesRoute: AuthenticatedProgramacaoTaludesRoute,
  AuthenticatedTaludesRoute: AuthenticatedTaludesRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
