/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPreventivaRouteImport } from './routes/_authenticated/preventiva'
import { Route as AuthenticatedOutrosRouteImport } from './routes/_authenticated/outros'
import { Route as AuthenticatedLimpezaRouteImport } from './routes/_authenticated/limpeza'
import { Route as AuthenticatedJardinagemRouteImport } from './routes/_authenticated/jardinagem'
import { Route as AuthenticatedCorretivaRouteImport } from './routes/_authenticated/corretiva'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAbastecimentoRouteImport } from './routes/_authenticated/abastecimento'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPreventivaRoute = AuthenticatedPreventivaRouteImport.update({
  id: '/_authenticated/preventiva',
  path: '/preventiva',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOutrosRoute = AuthenticatedOutrosRouteImport.update({
  id: '/_authenticated/outros',
  path: '/outros',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLimpezaRoute = AuthenticatedLimpezaRouteImport.update({
  id: '/_authenticated/limpeza',
  path: '/limpeza',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJardinagemRoute = AuthenticatedJardinagemRouteImport.update({
  id: '/_authenticated/jardinagem',
  path: '/jardinagem',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCorretivaRoute = AuthenticatedCorretivaRouteImport.update({
  id: '/_authenticated/corretiva',
  path: '/corretiva',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAbastecimentoRoute =
  AuthenticatedAbastecimentoRouteImport.update({
    id: '/_authenticated/abastecimento',
    path: '/abastecimento',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/abastecimento': typeof AuthenticatedAbastecimentoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/corretiva': typeof AuthenticatedCorretivaRoute
  '/jardinagem': typeof AuthenticatedJardinagemRoute
  '/limpeza': typeof AuthenticatedLimpezaRoute
  '/outros': typeof AuthenticatedOutrosRoute
  '/preventiva': typeof AuthenticatedPreventivaRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/abastecimento': typeof AuthenticatedAbastecimentoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/corretiva': typeof AuthenticatedCorretivaRoute
  '/jardinagem': typeof AuthenticatedJardinagemRoute
  '/limpeza': typeof AuthenticatedLimpezaRoute
  '/outros': typeof AuthenticatedOutrosRoute
  '/preventiva': typeof AuthenticatedPreventivaRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/abastecimento': typeof AuthenticatedAbastecimentoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/corretiva': typeof AuthenticatedCorretivaRoute
  '/_authenticated/jardinagem': typeof AuthenticatedJardinagemRoute
  '/_authenticated/limpeza': typeof AuthenticatedLimpezaRoute
  '/_authenticated/outros': typeof AuthenticatedOutrosRoute
  '/_authenticated/preventiva': typeof AuthenticatedPreventivaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/abastecimento'
    | '/configuracoes'
    | '/corretiva'
    | '/jardinagem'
    | '/limpeza'
    | '/outros'
    | '/preventiva'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/abastecimento'
    | '/configuracoes'
    | '/corretiva'
    | '/jardinagem'
    | '/limpeza'
    | '/outros'
    | '/preventiva'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/abastecimento'
    | '/_authenticated/configuracoes'
    | '/_authenticated/corretiva'
    | '/_authenticated/jardinagem'
    | '/_authenticated/limpeza'
    | '/_authenticated/outros'
    | '/_authenticated/preventiva'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAbastecimentoRoute: typeof AuthenticatedAbastecimentoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCorretivaRoute: typeof AuthenticatedCorretivaRoute
  AuthenticatedJardinagemRoute: typeof AuthenticatedJardinagemRoute
  AuthenticatedLimpezaRoute: typeof AuthenticatedLimpezaRoute
  AuthenticatedOutrosRoute: typeof AuthenticatedOutrosRoute
  AuthenticatedPreventivaRoute: typeof AuthenticatedPreventivaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/preventiva': {
      id: '/_authenticated/preventiva'
      path: '/preventiva'
      fullPath: '/preventiva'
      preLoaderRoute: typeof AuthenticatedPreventivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/outros': {
      id: '/_authenticated/outros'
      path: '/outros'
      fullPath: '/outros'
      preLoaderRoute: typeof AuthenticatedOutrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/limpeza': {
      id: '/_authenticated/limpeza'
      path: '/limpeza'
      fullPath: '/limpeza'
      preLoaderRoute: typeof AuthenticatedLimpezaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jardinagem': {
      id: '/_authenticated/jardinagem'
      path: '/jardinagem'
      fullPath: '/jardinagem'
      preLoaderRoute: typeof AuthenticatedJardinagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/corretiva': {
      id: '/_authenticated/corretiva'
      path: '/corretiva'
      fullPath: '/corretiva'
      preLoaderRoute: typeof AuthenticatedCorretivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/abastecimento': {
      id: '/_authenticated/abastecimento'
      path: '/abastecimento'
      fullPath: '/abastecimento'
      preLoaderRoute: typeof AuthenticatedAbastecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAbastecimentoRoute: AuthenticatedAbastecimentoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCorretivaRoute: AuthenticatedCorretivaRoute,
  AuthenticatedJardinagemRoute: AuthenticatedJardinagemRoute,
  AuthenticatedLimpezaRoute: AuthenticatedLimpezaRoute,
  AuthenticatedOutrosRoute: AuthenticatedOutrosRoute,
  AuthenticatedPreventivaRoute: AuthenticatedPreventivaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
