/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiBackorderReclassificarRouteImport } from './routes/api/backorder-reclassificar'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTaludesRouteImport } from './routes/_authenticated/taludes'
import { Route as AuthenticatedSegurancaTrabalhoRouteImport } from './routes/_authenticated/seguranca-trabalho'
import { Route as AuthenticatedRefrigeracaoPecasStatusRouteImport } from './routes/_authenticated/refrigeracao-pecas-status'
import { Route as AuthenticatedRefrigeracaoHistoricoRouteImport } from './routes/_authenticated/refrigeracao-historico'
import { Route as AuthenticatedRefrigeracaoGestorRouteImport } from './routes/_authenticated/refrigeracao-gestor'
import { Route as AuthenticatedRefrigeracaoRouteImport } from './routes/_authenticated/refrigeracao'
import { Route as AuthenticatedProgramacaoRouteImport } from './routes/_authenticated/programacao'
import { Route as AuthenticatedPreventivaAcRouteImport } from './routes/_authenticated/preventiva-ac'
import { Route as AuthenticatedPreventivaRouteImport } from './routes/_authenticated/preventiva'
import { Route as AuthenticatedPainelLegalRouteImport } from './routes/_authenticated/painel-legal'
import { Route as AuthenticatedOutrosRouteImport } from './routes/_authenticated/outros'
import { Route as AuthenticatedNotificacoesAdminRouteImport } from './routes/_authenticated/notificacoes-admin'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedLavanderiaRouteImport } from './routes/_authenticated/lavanderia'
import { Route as AuthenticatedDashboardChamadosRouteImport } from './routes/_authenticated/dashboard-chamados'
import { Route as AuthenticatedCorretivaPecasStatusRouteImport } from './routes/_authenticated/corretiva-pecas-status'
import { Route as AuthenticatedCorretivaHistoricoRouteImport } from './routes/_authenticated/corretiva-historico'
import { Route as AuthenticatedCorretivaGestorRouteImport } from './routes/_authenticated/corretiva-gestor'
import { Route as AuthenticatedCorretivaRouteImport } from './routes/_authenticated/corretiva'
import { Route as AuthenticatedControleMateriaisRouteImport } from './routes/_authenticated/controle-materiais'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClimaTempoRouteImport } from './routes/_authenticated/clima-tempo'
import { Route as AuthenticatedBaseAtivosRouteImport } from './routes/_authenticated/base-ativos'
import { Route as AuthenticatedBackorderRouteImport } from './routes/_authenticated/backorder'
import { Route as AuthenticatedBacklogInteligenteRouteImport } from './routes/_authenticated/backlog-inteligente'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedApontamentosRouteImport } from './routes/_authenticated/apontamentos'
import { Route as AuthenticatedAbastecimentoRouteImport } from './routes/_authenticated/abastecimento'
import { Route as ApiPublicImgbbUploadRouteImport } from './routes/api/public/imgbb-upload'
import { Route as ApiPublicClimaForecastRouteImport } from './routes/api/public/clima-forecast'
import { Route as ApiPublicClimaRouteImport } from './routes/api/public/clima'
import { Route as AuthenticatedInteligenciaAtivosPreencherRouteImport } from './routes/_authenticated/inteligencia-ativos.preencher'
import { Route as AuthenticatedInteligenciaAtivosNaoEncontradosRouteImport } from './routes/_authenticated/inteligencia-ativos.nao-encontrados'
import { Route as AuthenticatedInteligenciaAtivosHistoricoRouteImport } from './routes/_authenticated/inteligencia-ativos.historico'
import { Route as ApiPublicHooksWeatherMonitorRouteImport } from './routes/api/public/hooks/weather-monitor'
import { Route as ApiPublicHooksPluviometroRouteImport } from './routes/api/public/hooks/pluviometro'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiBackorderReclassificarRoute =
  ApiBackorderReclassificarRouteImport.update({
    id: '/api/backorder-reclassificar',
    path: '/api/backorder-reclassificar',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaludesRoute = AuthenticatedTaludesRouteImport.update({
  id: '/taludes',
  path: '/taludes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSegurancaTrabalhoRoute =
  AuthenticatedSegurancaTrabalhoRouteImport.update({
    id: '/seguranca-trabalho',
    path: '/seguranca-trabalho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRefrigeracaoPecasStatusRoute =
  AuthenticatedRefrigeracaoPecasStatusRouteImport.update({
    id: '/refrigeracao-pecas-status',
    path: '/refrigeracao-pecas-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRefrigeracaoHistoricoRoute =
  AuthenticatedRefrigeracaoHistoricoRouteImport.update({
    id: '/refrigeracao-historico',
    path: '/refrigeracao-historico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRefrigeracaoGestorRoute =
  AuthenticatedRefrigeracaoGestorRouteImport.update({
    id: '/refrigeracao-gestor',
    path: '/refrigeracao-gestor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRefrigeracaoRoute =
  AuthenticatedRefrigeracaoRouteImport.update({
    id: '/refrigeracao',
    path: '/refrigeracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgramacaoRoute =
  AuthenticatedProgramacaoRouteImport.update({
    id: '/programacao',
    path: '/programacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreventivaAcRoute =
  AuthenticatedPreventivaAcRouteImport.update({
    id: '/preventiva-ac',
    path: '/preventiva-ac',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreventivaRoute = AuthenticatedPreventivaRouteImport.update({
  id: '/preventiva',
  path: '/preventiva',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelLegalRoute =
  AuthenticatedPainelLegalRouteImport.update({
    id: '/painel-legal',
    path: '/painel-legal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutrosRoute = AuthenticatedOutrosRouteImport.update({
  id: '/outros',
  path: '/outros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesAdminRoute =
  AuthenticatedNotificacoesAdminRouteImport.update({
    id: '/notificacoes-admin',
    path: '/notificacoes-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLavanderiaRoute = AuthenticatedLavanderiaRouteImport.update({
  id: '/lavanderia',
  path: '/lavanderia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardChamadosRoute =
  AuthenticatedDashboardChamadosRouteImport.update({
    id: '/dashboard-chamados',
    path: '/dashboard-chamados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCorretivaPecasStatusRoute =
  AuthenticatedCorretivaPecasStatusRouteImport.update({
    id: '/corretiva-pecas-status',
    path: '/corretiva-pecas-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCorretivaHistoricoRoute =
  AuthenticatedCorretivaHistoricoRouteImport.update({
    id: '/corretiva-historico',
    path: '/corretiva-historico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCorretivaGestorRoute =
  AuthenticatedCorretivaGestorRouteImport.update({
    id: '/corretiva-gestor',
    path: '/corretiva-gestor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCorretivaRoute = AuthenticatedCorretivaRouteImport.update({
  id: '/corretiva',
  path: '/corretiva',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedControleMateriaisRoute =
  AuthenticatedControleMateriaisRouteImport.update({
    id: '/controle-materiais',
    path: '/controle-materiais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClimaTempoRoute = AuthenticatedClimaTempoRouteImport.update({
  id: '/clima-tempo',
  path: '/clima-tempo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaseAtivosRoute = AuthenticatedBaseAtivosRouteImport.update({
  id: '/base-ativos',
  path: '/base-ativos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackorderRoute = AuthenticatedBackorderRouteImport.update({
  id: '/backorder',
  path: '/backorder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBacklogInteligenteRoute =
  AuthenticatedBacklogInteligenteRouteImport.update({
    id: '/backlog-inteligente',
    path: '/backlog-inteligente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApontamentosRoute =
  AuthenticatedApontamentosRouteImport.update({
    id: '/apontamentos',
    path: '/apontamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAbastecimentoRoute =
  AuthenticatedAbastecimentoRouteImport.update({
    id: '/abastecimento',
    path: '/abastecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicImgbbUploadRoute = ApiPublicImgbbUploadRouteImport.update({
  id: '/api/public/imgbb-upload',
  path: '/api/public/imgbb-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClimaForecastRoute = ApiPublicClimaForecastRouteImport.update({
  id: '/api/public/clima-forecast',
  path: '/api/public/clima-forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClimaRoute = ApiPublicClimaRouteImport.update({
  id: '/api/public/clima',
  path: '/api/public/clima',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInteligenciaAtivosPreencherRoute =
  AuthenticatedInteligenciaAtivosPreencherRouteImport.update({
    id: '/inteligencia-ativos/preencher',
    path: '/inteligencia-ativos/preencher',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInteligenciaAtivosNaoEncontradosRoute =
  AuthenticatedInteligenciaAtivosNaoEncontradosRouteImport.update({
    id: '/inteligencia-ativos/nao-encontrados',
    path: '/inteligencia-ativos/nao-encontrados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInteligenciaAtivosHistoricoRoute =
  AuthenticatedInteligenciaAtivosHistoricoRouteImport.update({
    id: '/inteligencia-ativos/historico',
    path: '/inteligencia-ativos/historico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksWeatherMonitorRoute =
  ApiPublicHooksWeatherMonitorRouteImport.update({
    id: '/api/public/hooks/weather-monitor',
    path: '/api/public/hooks/weather-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPluviometroRoute =
  ApiPublicHooksPluviometroRouteImport.update({
    id: '/api/public/hooks/pluviometro',
    path: '/api/public/hooks/pluviometro',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/abastecimento': typeof AuthenticatedAbastecimentoRoute
  '/apontamentos': typeof AuthenticatedApontamentosRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/backlog-inteligente': typeof AuthenticatedBacklogInteligenteRoute
  '/backorder': typeof AuthenticatedBackorderRoute
  '/base-ativos': typeof AuthenticatedBaseAtivosRoute
  '/clima-tempo': typeof AuthenticatedClimaTempoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/controle-materiais': typeof AuthenticatedControleMateriaisRoute
  '/corretiva': typeof AuthenticatedCorretivaRoute
  '/corretiva-gestor': typeof AuthenticatedCorretivaGestorRoute
  '/corretiva-historico': typeof AuthenticatedCorretivaHistoricoRoute
  '/corretiva-pecas-status': typeof AuthenticatedCorretivaPecasStatusRoute
  '/dashboard-chamados': typeof AuthenticatedDashboardChamadosRoute
  '/lavanderia': typeof AuthenticatedLavanderiaRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/notificacoes-admin': typeof AuthenticatedNotificacoesAdminRoute
  '/outros': typeof AuthenticatedOutrosRoute
  '/painel-legal': typeof AuthenticatedPainelLegalRoute
  '/preventiva': typeof AuthenticatedPreventivaRoute
  '/preventiva-ac': typeof AuthenticatedPreventivaAcRoute
  '/programacao': typeof AuthenticatedProgramacaoRoute
  '/refrigeracao': typeof AuthenticatedRefrigeracaoRoute
  '/refrigeracao-gestor': typeof AuthenticatedRefrigeracaoGestorRoute
  '/refrigeracao-historico': typeof AuthenticatedRefrigeracaoHistoricoRoute
  '/refrigeracao-pecas-status': typeof AuthenticatedRefrigeracaoPecasStatusRoute
  '/seguranca-trabalho': typeof AuthenticatedSegurancaTrabalhoRoute
  '/taludes': typeof AuthenticatedTaludesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/backorder-reclassificar': typeof ApiBackorderReclassificarRoute
  '/inteligencia-ativos/historico': typeof AuthenticatedInteligenciaAtivosHistoricoRoute
  '/inteligencia-ativos/nao-encontrados': typeof AuthenticatedInteligenciaAtivosNaoEncontradosRoute
  '/inteligencia-ativos/preencher': typeof AuthenticatedInteligenciaAtivosPreencherRoute
  '/api/public/clima': typeof ApiPublicClimaRoute
  '/api/public/clima-forecast': typeof ApiPublicClimaForecastRoute
  '/api/public/imgbb-upload': typeof ApiPublicImgbbUploadRoute
  '/api/public/hooks/pluviometro': typeof ApiPublicHooksPluviometroRoute
  '/api/public/hooks/weather-monitor': typeof ApiPublicHooksWeatherMonitorRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/abastecimento': typeof AuthenticatedAbastecimentoRoute
  '/apontamentos': typeof AuthenticatedApontamentosRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/backlog-inteligente': typeof AuthenticatedBacklogInteligenteRoute
  '/backorder': typeof AuthenticatedBackorderRoute
  '/base-ativos': typeof AuthenticatedBaseAtivosRoute
  '/clima-tempo': typeof AuthenticatedClimaTempoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/controle-materiais': typeof AuthenticatedControleMateriaisRoute
  '/corretiva': typeof AuthenticatedCorretivaRoute
  '/corretiva-gestor': typeof AuthenticatedCorretivaGestorRoute
  '/corretiva-historico': typeof AuthenticatedCorretivaHistoricoRoute
  '/corretiva-pecas-status': typeof AuthenticatedCorretivaPecasStatusRoute
  '/dashboard-chamados': typeof AuthenticatedDashboardChamadosRoute
  '/lavanderia': typeof AuthenticatedLavanderiaRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/notificacoes-admin': typeof AuthenticatedNotificacoesAdminRoute
  '/outros': typeof AuthenticatedOutrosRoute
  '/painel-legal': typeof AuthenticatedPainelLegalRoute
  '/preventiva': typeof AuthenticatedPreventivaRoute
  '/preventiva-ac': typeof AuthenticatedPreventivaAcRoute
  '/programacao': typeof AuthenticatedProgramacaoRoute
  '/refrigeracao': typeof AuthenticatedRefrigeracaoRoute
  '/refrigeracao-gestor': typeof AuthenticatedRefrigeracaoGestorRoute
  '/refrigeracao-historico': typeof AuthenticatedRefrigeracaoHistoricoRoute
  '/refrigeracao-pecas-status': typeof AuthenticatedRefrigeracaoPecasStatusRoute
  '/seguranca-trabalho': typeof AuthenticatedSegurancaTrabalhoRoute
  '/taludes': typeof AuthenticatedTaludesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/backorder-reclassificar': typeof ApiBackorderReclassificarRoute
  '/': typeof AuthenticatedIndexRoute
  '/inteligencia-ativos/historico': typeof AuthenticatedInteligenciaAtivosHistoricoRoute
  '/inteligencia-ativos/nao-encontrados': typeof AuthenticatedInteligenciaAtivosNaoEncontradosRoute
  '/inteligencia-ativos/preencher': typeof AuthenticatedInteligenciaAtivosPreencherRoute
  '/api/public/clima': typeof ApiPublicClimaRoute
  '/api/public/clima-forecast': typeof ApiPublicClimaForecastRoute
  '/api/public/imgbb-upload': typeof ApiPublicImgbbUploadRoute
  '/api/public/hooks/pluviometro': typeof ApiPublicHooksPluviometroRoute
  '/api/public/hooks/weather-monitor': typeof ApiPublicHooksWeatherMonitorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/_authenticated/abastecimento': typeof AuthenticatedAbastecimentoRoute
  '/_authenticated/apontamentos': typeof AuthenticatedApontamentosRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/backlog-inteligente': typeof AuthenticatedBacklogInteligenteRoute
  '/_authenticated/backorder': typeof AuthenticatedBackorderRoute
  '/_authenticated/base-ativos': typeof AuthenticatedBaseAtivosRoute
  '/_authenticated/clima-tempo': typeof AuthenticatedClimaTempoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/controle-materiais': typeof AuthenticatedControleMateriaisRoute
  '/_authenticated/corretiva': typeof AuthenticatedCorretivaRoute
  '/_authenticated/corretiva-gestor': typeof AuthenticatedCorretivaGestorRoute
  '/_authenticated/corretiva-historico': typeof AuthenticatedCorretivaHistoricoRoute
  '/_authenticated/corretiva-pecas-status': typeof AuthenticatedCorretivaPecasStatusRoute
  '/_authenticated/dashboard-chamados': typeof AuthenticatedDashboardChamadosRoute
  '/_authenticated/lavanderia': typeof AuthenticatedLavanderiaRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/notificacoes-admin': typeof AuthenticatedNotificacoesAdminRoute
  '/_authenticated/outros': typeof AuthenticatedOutrosRoute
  '/_authenticated/painel-legal': typeof AuthenticatedPainelLegalRoute
  '/_authenticated/preventiva': typeof AuthenticatedPreventivaRoute
  '/_authenticated/preventiva-ac': typeof AuthenticatedPreventivaAcRoute
  '/_authenticated/programacao': typeof AuthenticatedProgramacaoRoute
  '/_authenticated/refrigeracao': typeof AuthenticatedRefrigeracaoRoute
  '/_authenticated/refrigeracao-gestor': typeof AuthenticatedRefrigeracaoGestorRoute
  '/_authenticated/refrigeracao-historico': typeof AuthenticatedRefrigeracaoHistoricoRoute
  '/_authenticated/refrigeracao-pecas-status': typeof AuthenticatedRefrigeracaoPecasStatusRoute
  '/_authenticated/seguranca-trabalho': typeof AuthenticatedSegurancaTrabalhoRoute
  '/_authenticated/taludes': typeof AuthenticatedTaludesRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/backorder-reclassificar': typeof ApiBackorderReclassificarRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/inteligencia-ativos/historico': typeof AuthenticatedInteligenciaAtivosHistoricoRoute
  '/_authenticated/inteligencia-ativos/nao-encontrados': typeof AuthenticatedInteligenciaAtivosNaoEncontradosRoute
  '/_authenticated/inteligencia-ativos/preencher': typeof AuthenticatedInteligenciaAtivosPreencherRoute
  '/api/public/clima': typeof ApiPublicClimaRoute
  '/api/public/clima-forecast': typeof ApiPublicClimaForecastRoute
  '/api/public/imgbb-upload': typeof ApiPublicImgbbUploadRoute
  '/api/public/hooks/pluviometro': typeof ApiPublicHooksPluviometroRoute
  '/api/public/hooks/weather-monitor': typeof ApiPublicHooksWeatherMonitorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/abastecimento'
    | '/apontamentos'
    | '/auditoria'
    | '/backlog-inteligente'
    | '/backorder'
    | '/base-ativos'
    | '/clima-tempo'
    | '/configuracoes'
    | '/controle-materiais'
    | '/corretiva'
    | '/corretiva-gestor'
    | '/corretiva-historico'
    | '/corretiva-pecas-status'
    | '/dashboard-chamados'
    | '/lavanderia'
    | '/notificacoes'
    | '/notificacoes-admin'
    | '/outros'
    | '/painel-legal'
    | '/preventiva'
    | '/preventiva-ac'
    | '/programacao'
    | '/refrigeracao'
    | '/refrigeracao-gestor'
    | '/refrigeracao-historico'
    | '/refrigeracao-pecas-status'
    | '/seguranca-trabalho'
    | '/taludes'
    | '/usuarios'
    | '/api/backorder-reclassificar'
    | '/inteligencia-ativos/historico'
    | '/inteligencia-ativos/nao-encontrados'
    | '/inteligencia-ativos/preencher'
    | '/api/public/clima'
    | '/api/public/clima-forecast'
    | '/api/public/imgbb-upload'
    | '/api/public/hooks/pluviometro'
    | '/api/public/hooks/weather-monitor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/contato'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/abastecimento'
    | '/apontamentos'
    | '/auditoria'
    | '/backlog-inteligente'
    | '/backorder'
    | '/base-ativos'
    | '/clima-tempo'
    | '/configuracoes'
    | '/controle-materiais'
    | '/corretiva'
    | '/corretiva-gestor'
    | '/corretiva-historico'
    | '/corretiva-pecas-status'
    | '/dashboard-chamados'
    | '/lavanderia'
    | '/notificacoes'
    | '/notificacoes-admin'
    | '/outros'
    | '/painel-legal'
    | '/preventiva'
    | '/preventiva-ac'
    | '/programacao'
    | '/refrigeracao'
    | '/refrigeracao-gestor'
    | '/refrigeracao-historico'
    | '/refrigeracao-pecas-status'
    | '/seguranca-trabalho'
    | '/taludes'
    | '/usuarios'
    | '/api/backorder-reclassificar'
    | '/'
    | '/inteligencia-ativos/historico'
    | '/inteligencia-ativos/nao-encontrados'
    | '/inteligencia-ativos/preencher'
    | '/api/public/clima'
    | '/api/public/clima-forecast'
    | '/api/public/imgbb-upload'
    | '/api/public/hooks/pluviometro'
    | '/api/public/hooks/weather-monitor'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/_authenticated/abastecimento'
    | '/_authenticated/apontamentos'
    | '/_authenticated/auditoria'
    | '/_authenticated/backlog-inteligente'
    | '/_authenticated/backorder'
    | '/_authenticated/base-ativos'
    | '/_authenticated/clima-tempo'
    | '/_authenticated/configuracoes'
    | '/_authenticated/controle-materiais'
    | '/_authenticated/corretiva'
    | '/_authenticated/corretiva-gestor'
    | '/_authenticated/corretiva-historico'
    | '/_authenticated/corretiva-pecas-status'
    | '/_authenticated/dashboard-chamados'
    | '/_authenticated/lavanderia'
    | '/_authenticated/notificacoes'
    | '/_authenticated/notificacoes-admin'
    | '/_authenticated/outros'
    | '/_authenticated/painel-legal'
    | '/_authenticated/preventiva'
    | '/_authenticated/preventiva-ac'
    | '/_authenticated/programacao'
    | '/_authenticated/refrigeracao'
    | '/_authenticated/refrigeracao-gestor'
    | '/_authenticated/refrigeracao-historico'
    | '/_authenticated/refrigeracao-pecas-status'
    | '/_authenticated/seguranca-trabalho'
    | '/_authenticated/taludes'
    | '/_authenticated/usuarios'
    | '/api/backorder-reclassificar'
    | '/_authenticated/'
    | '/_authenticated/inteligencia-ativos/historico'
    | '/_authenticated/inteligencia-ativos/nao-encontrados'
    | '/_authenticated/inteligencia-ativos/preencher'
    | '/api/public/clima'
    | '/api/public/clima-forecast'
    | '/api/public/imgbb-upload'
    | '/api/public/hooks/pluviometro'
    | '/api/public/hooks/weather-monitor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  ApiBackorderReclassificarRoute: typeof ApiBackorderReclassificarRoute
  ApiPublicClimaRoute: typeof ApiPublicClimaRoute
  ApiPublicClimaForecastRoute: typeof ApiPublicClimaForecastRoute
  ApiPublicImgbbUploadRoute: typeof ApiPublicImgbbUploadRoute
  ApiPublicHooksPluviometroRoute: typeof ApiPublicHooksPluviometroRoute
  ApiPublicHooksWeatherMonitorRoute: typeof ApiPublicHooksWeatherMonitorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/backorder-reclassificar': {
      id: '/api/backorder-reclassificar'
      path: '/api/backorder-reclassificar'
      fullPath: '/api/backorder-reclassificar'
      preLoaderRoute: typeof ApiBackorderReclassificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taludes': {
      id: '/_authenticated/taludes'
      path: '/taludes'
      fullPath: '/taludes'
      preLoaderRoute: typeof AuthenticatedTaludesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seguranca-trabalho': {
      id: '/_authenticated/seguranca-trabalho'
      path: '/seguranca-trabalho'
      fullPath: '/seguranca-trabalho'
      preLoaderRoute: typeof AuthenticatedSegurancaTrabalhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refrigeracao-pecas-status': {
      id: '/_authenticated/refrigeracao-pecas-status'
      path: '/refrigeracao-pecas-status'
      fullPath: '/refrigeracao-pecas-status'
      preLoaderRoute: typeof AuthenticatedRefrigeracaoPecasStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refrigeracao-historico': {
      id: '/_authenticated/refrigeracao-historico'
      path: '/refrigeracao-historico'
      fullPath: '/refrigeracao-historico'
      preLoaderRoute: typeof AuthenticatedRefrigeracaoHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refrigeracao-gestor': {
      id: '/_authenticated/refrigeracao-gestor'
      path: '/refrigeracao-gestor'
      fullPath: '/refrigeracao-gestor'
      preLoaderRoute: typeof AuthenticatedRefrigeracaoGestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refrigeracao': {
      id: '/_authenticated/refrigeracao'
      path: '/refrigeracao'
      fullPath: '/refrigeracao'
      preLoaderRoute: typeof AuthenticatedRefrigeracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programacao': {
      id: '/_authenticated/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof AuthenticatedProgramacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preventiva-ac': {
      id: '/_authenticated/preventiva-ac'
      path: '/preventiva-ac'
      fullPath: '/preventiva-ac'
      preLoaderRoute: typeof AuthenticatedPreventivaAcRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preventiva': {
      id: '/_authenticated/preventiva'
      path: '/preventiva'
      fullPath: '/preventiva'
      preLoaderRoute: typeof AuthenticatedPreventivaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-legal': {
      id: '/_authenticated/painel-legal'
      path: '/painel-legal'
      fullPath: '/painel-legal'
      preLoaderRoute: typeof AuthenticatedPainelLegalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outros': {
      id: '/_authenticated/outros'
      path: '/outros'
      fullPath: '/outros'
      preLoaderRoute: typeof AuthenticatedOutrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes-admin': {
      id: '/_authenticated/notificacoes-admin'
      path: '/notificacoes-admin'
      fullPath: '/notificacoes-admin'
      preLoaderRoute: typeof AuthenticatedNotificacoesAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lavanderia': {
      id: '/_authenticated/lavanderia'
      path: '/lavanderia'
      fullPath: '/lavanderia'
      preLoaderRoute: typeof AuthenticatedLavanderiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-chamados': {
      id: '/_authenticated/dashboard-chamados'
      path: '/dashboard-chamados'
      fullPath: '/dashboard-chamados'
      preLoaderRoute: typeof AuthenticatedDashboardChamadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corretiva-pecas-status': {
      id: '/_authenticated/corretiva-pecas-status'
      path: '/corretiva-pecas-status'
      fullPath: '/corretiva-pecas-status'
      preLoaderRoute: typeof AuthenticatedCorretivaPecasStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corretiva-historico': {
      id: '/_authenticated/corretiva-historico'
      path: '/corretiva-historico'
      fullPath: '/corretiva-historico'
      preLoaderRoute: typeof AuthenticatedCorretivaHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corretiva-gestor': {
      id: '/_authenticated/corretiva-gestor'
      path: '/corretiva-gestor'
      fullPath: '/corretiva-gestor'
      preLoaderRoute: typeof AuthenticatedCorretivaGestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corretiva': {
      id: '/_authenticated/corretiva'
      path: '/corretiva'
      fullPath: '/corretiva'
      preLoaderRoute: typeof AuthenticatedCorretivaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/controle-materiais': {
      id: '/_authenticated/controle-materiais'
      path: '/controle-materiais'
      fullPath: '/controle-materiais'
      preLoaderRoute: typeof AuthenticatedControleMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clima-tempo': {
      id: '/_authenticated/clima-tempo'
      path: '/clima-tempo'
      fullPath: '/clima-tempo'
      preLoaderRoute: typeof AuthenticatedClimaTempoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-ativos': {
      id: '/_authenticated/base-ativos'
      path: '/base-ativos'
      fullPath: '/base-ativos'
      preLoaderRoute: typeof AuthenticatedBaseAtivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backorder': {
      id: '/_authenticated/backorder'
      path: '/backorder'
      fullPath: '/backorder'
      preLoaderRoute: typeof AuthenticatedBackorderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backlog-inteligente': {
      id: '/_authenticated/backlog-inteligente'
      path: '/backlog-inteligente'
      fullPath: '/backlog-inteligente'
      preLoaderRoute: typeof AuthenticatedBacklogInteligenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apontamentos': {
      id: '/_authenticated/apontamentos'
      path: '/apontamentos'
      fullPath: '/apontamentos'
      preLoaderRoute: typeof AuthenticatedApontamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abastecimento': {
      id: '/_authenticated/abastecimento'
      path: '/abastecimento'
      fullPath: '/abastecimento'
      preLoaderRoute: typeof AuthenticatedAbastecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/imgbb-upload': {
      id: '/api/public/imgbb-upload'
      path: '/api/public/imgbb-upload'
      fullPath: '/api/public/imgbb-upload'
      preLoaderRoute: typeof ApiPublicImgbbUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clima-forecast': {
      id: '/api/public/clima-forecast'
      path: '/api/public/clima-forecast'
      fullPath: '/api/public/clima-forecast'
      preLoaderRoute: typeof ApiPublicClimaForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clima': {
      id: '/api/public/clima'
      path: '/api/public/clima'
      fullPath: '/api/public/clima'
      preLoaderRoute: typeof ApiPublicClimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inteligencia-ativos/preencher': {
      id: '/_authenticated/inteligencia-ativos/preencher'
      path: '/inteligencia-ativos/preencher'
      fullPath: '/inteligencia-ativos/preencher'
      preLoaderRoute: typeof AuthenticatedInteligenciaAtivosPreencherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inteligencia-ativos/nao-encontrados': {
      id: '/_authenticated/inteligencia-ativos/nao-encontrados'
      path: '/inteligencia-ativos/nao-encontrados'
      fullPath: '/inteligencia-ativos/nao-encontrados'
      preLoaderRoute: typeof AuthenticatedInteligenciaAtivosNaoEncontradosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inteligencia-ativos/historico': {
      id: '/_authenticated/inteligencia-ativos/historico'
      path: '/inteligencia-ativos/historico'
      fullPath: '/inteligencia-ativos/historico'
      preLoaderRoute: typeof AuthenticatedInteligenciaAtivosHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/weather-monitor': {
      id: '/api/public/hooks/weather-monitor'
      path: '/api/public/hooks/weather-monitor'
      fullPath: '/api/public/hooks/weather-monitor'
      preLoaderRoute: typeof ApiPublicHooksWeatherMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pluviometro': {
      id: '/api/public/hooks/pluviometro'
      path: '/api/public/hooks/pluviometro'
      fullPath: '/api/public/hooks/pluviometro'
      preLoaderRoute: typeof ApiPublicHooksPluviometroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbastecimentoRoute: typeof AuthenticatedAbastecimentoRoute
  AuthenticatedApontamentosRoute: typeof AuthenticatedApontamentosRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedBacklogInteligenteRoute: typeof AuthenticatedBacklogInteligenteRoute
  AuthenticatedBackorderRoute: typeof AuthenticatedBackorderRoute
  AuthenticatedBaseAtivosRoute: typeof AuthenticatedBaseAtivosRoute
  AuthenticatedClimaTempoRoute: typeof AuthenticatedClimaTempoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedControleMateriaisRoute: typeof AuthenticatedControleMateriaisRoute
  AuthenticatedCorretivaRoute: typeof AuthenticatedCorretivaRoute
  AuthenticatedCorretivaGestorRoute: typeof AuthenticatedCorretivaGestorRoute
  AuthenticatedCorretivaHistoricoRoute: typeof AuthenticatedCorretivaHistoricoRoute
  AuthenticatedCorretivaPecasStatusRoute: typeof AuthenticatedCorretivaPecasStatusRoute
  AuthenticatedDashboardChamadosRoute: typeof AuthenticatedDashboardChamadosRoute
  AuthenticatedLavanderiaRoute: typeof AuthenticatedLavanderiaRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedNotificacoesAdminRoute: typeof AuthenticatedNotificacoesAdminRoute
  AuthenticatedOutrosRoute: typeof AuthenticatedOutrosRoute
  AuthenticatedPainelLegalRoute: typeof AuthenticatedPainelLegalRoute
  AuthenticatedPreventivaRoute: typeof AuthenticatedPreventivaRoute
  AuthenticatedPreventivaAcRoute: typeof AuthenticatedPreventivaAcRoute
  AuthenticatedProgramacaoRoute: typeof AuthenticatedProgramacaoRoute
  AuthenticatedRefrigeracaoRoute: typeof AuthenticatedRefrigeracaoRoute
  AuthenticatedRefrigeracaoGestorRoute: typeof AuthenticatedRefrigeracaoGestorRoute
  AuthenticatedRefrigeracaoHistoricoRoute: typeof AuthenticatedRefrigeracaoHistoricoRoute
  AuthenticatedRefrigeracaoPecasStatusRoute: typeof AuthenticatedRefrigeracaoPecasStatusRoute
  AuthenticatedSegurancaTrabalhoRoute: typeof AuthenticatedSegurancaTrabalhoRoute
  AuthenticatedTaludesRoute: typeof AuthenticatedTaludesRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInteligenciaAtivosHistoricoRoute: typeof AuthenticatedInteligenciaAtivosHistoricoRoute
  AuthenticatedInteligenciaAtivosNaoEncontradosRoute: typeof AuthenticatedInteligenciaAtivosNaoEncontradosRoute
  AuthenticatedInteligenciaAtivosPreencherRoute: typeof AuthenticatedInteligenciaAtivosPreencherRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbastecimentoRoute: AuthenticatedAbastecimentoRoute,
  AuthenticatedApontamentosRoute: AuthenticatedApontamentosRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedBacklogInteligenteRoute: AuthenticatedBacklogInteligenteRoute,
  AuthenticatedBackorderRoute: AuthenticatedBackorderRoute,
  AuthenticatedBaseAtivosRoute: AuthenticatedBaseAtivosRoute,
  AuthenticatedClimaTempoRoute: AuthenticatedClimaTempoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedControleMateriaisRoute: AuthenticatedControleMateriaisRoute,
  AuthenticatedCorretivaRoute: AuthenticatedCorretivaRoute,
  AuthenticatedCorretivaGestorRoute: AuthenticatedCorretivaGestorRoute,
  AuthenticatedCorretivaHistoricoRoute: AuthenticatedCorretivaHistoricoRoute,
  AuthenticatedCorretivaPecasStatusRoute:
    AuthenticatedCorretivaPecasStatusRoute,
  AuthenticatedDashboardChamadosRoute: AuthenticatedDashboardChamadosRoute,
  AuthenticatedLavanderiaRoute: AuthenticatedLavanderiaRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedNotificacoesAdminRoute: AuthenticatedNotificacoesAdminRoute,
  AuthenticatedOutrosRoute: AuthenticatedOutrosRoute,
  AuthenticatedPainelLegalRoute: AuthenticatedPainelLegalRoute,
  AuthenticatedPreventivaRoute: AuthenticatedPreventivaRoute,
  AuthenticatedPreventivaAcRoute: AuthenticatedPreventivaAcRoute,
  AuthenticatedProgramacaoRoute: AuthenticatedProgramacaoRoute,
  AuthenticatedRefrigeracaoRoute: AuthenticatedRefrigeracaoRoute,
  AuthenticatedRefrigeracaoGestorRoute: AuthenticatedRefrigeracaoGestorRoute,
  AuthenticatedRefrigeracaoHistoricoRoute:
    AuthenticatedRefrigeracaoHistoricoRoute,
  AuthenticatedRefrigeracaoPecasStatusRoute:
    AuthenticatedRefrigeracaoPecasStatusRoute,
  AuthenticatedSegurancaTrabalhoRoute: AuthenticatedSegurancaTrabalhoRoute,
  AuthenticatedTaludesRoute: AuthenticatedTaludesRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInteligenciaAtivosHistoricoRoute:
    AuthenticatedInteligenciaAtivosHistoricoRoute,
  AuthenticatedInteligenciaAtivosNaoEncontradosRoute:
    AuthenticatedInteligenciaAtivosNaoEncontradosRoute,
  AuthenticatedInteligenciaAtivosPreencherRoute:
    AuthenticatedInteligenciaAtivosPreencherRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  ApiBackorderReclassificarRoute: ApiBackorderReclassificarRoute,
  ApiPublicClimaRoute: ApiPublicClimaRoute,
  ApiPublicClimaForecastRoute: ApiPublicClimaForecastRoute,
  ApiPublicImgbbUploadRoute: ApiPublicImgbbUploadRoute,
  ApiPublicHooksPluviometroRoute: ApiPublicHooksPluviometroRoute,
  ApiPublicHooksWeatherMonitorRoute: ApiPublicHooksWeatherMonitorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
