-- =====================================================================
-- Filtros de água: ativos, eventos e workflow com SLA
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.agua_filtro_ativos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ponto_id uuid NOT NULL REFERENCES public.agua_pontos(id) ON DELETE CASCADE,
  codigo text,
  marca text,
  modelo text,
  numero_serie text,
  tipo_filtro text NOT NULL DEFAULT 'refil',
  local_instalacao text,
  instalado_em date,
  ultima_troca date,
  periodicidade_dias integer NOT NULL DEFAULT 180,
  proxima_troca date,
  situacao text NOT NULL DEFAULT 'ativo',
  observacao text,
  criado_por uuid,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT agua_filtro_ativos_periodicidade_chk CHECK (periodicidade_dias BETWEEN 1 AND 3650),
  CONSTRAINT agua_filtro_ativos_situacao_chk CHECK (situacao IN ('ativo','inativo','substituido'))
);

CREATE UNIQUE INDEX IF NOT EXISTS agua_filtro_ativos_serie_uidx
  ON public.agua_filtro_ativos (lower(numero_serie))
  WHERE numero_serie IS NOT NULL AND numero_serie <> '';
CREATE INDEX IF NOT EXISTS agua_filtro_ativos_ponto_idx ON public.agua_filtro_ativos (ponto_id);
CREATE INDEX IF NOT EXISTS agua_filtro_ativos_proxima_idx ON public.agua_filtro_ativos (proxima_troca);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.agua_filtro_ativos TO authenticated;
GRANT ALL ON public.agua_filtro_ativos TO service_role;
ALTER TABLE public.agua_filtro_ativos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "agua_filtro_ativos_select" ON public.agua_filtro_ativos
  FOR SELECT TO authenticated USING (public.agua_can('read'));
CREATE POLICY "agua_filtro_ativos_insert" ON public.agua_filtro_ativos
  FOR INSERT TO authenticated WITH CHECK (public.agua_can('create'));
CREATE POLICY "agua_filtro_ativos_update" ON public.agua_filtro_ativos
  FOR UPDATE TO authenticated USING (public.agua_can('update')) WITH CHECK (public.agua_can('update'));
CREATE POLICY "agua_filtro_ativos_delete" ON public.agua_filtro_ativos
  FOR DELETE TO authenticated USING (public.agua_is_gestor());

-- --------------------------------------------------------------------
-- Colunas novas nas solicitações
-- --------------------------------------------------------------------
ALTER TABLE public.agua_filtro_solicitacoes
  ADD COLUMN IF NOT EXISTS ativo_id uuid REFERENCES public.agua_filtro_ativos(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS origem text NOT NULL DEFAULT 'gestor',
  ADD COLUMN IF NOT EXISTS sla_horas integer,
  ADD COLUMN IF NOT EXISTS vence_em timestamptz,
  ADD COLUMN IF NOT EXISTS atendida_por uuid,
  ADD COLUMN IF NOT EXISTS foto_conclusao_url text,
  ADD COLUMN IF NOT EXISTS observacao_conclusao text,
  ADD COLUMN IF NOT EXISTS motivo_cancelamento text,
  ADD COLUMN IF NOT EXISTS numero bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS agua_filtro_solic_vence_idx
  ON public.agua_filtro_solicitacoes (vence_em)
  WHERE situacao IN ('aberta','em_atendimento');

-- --------------------------------------------------------------------
-- Trilha de eventos (append-only)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agua_filtro_eventos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  solicitacao_id uuid NOT NULL REFERENCES public.agua_filtro_solicitacoes(id) ON DELETE CASCADE,
  tipo text NOT NULL,
  situacao_anterior text,
  situacao_nova text,
  comentario text,
  foto_url text,
  autor uuid,
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT agua_filtro_eventos_tipo_chk CHECK (
    tipo IN ('abertura','triagem','programacao','execucao','conclusao','cancelamento','comentario')
  )
);

CREATE INDEX IF NOT EXISTS agua_filtro_eventos_solic_idx
  ON public.agua_filtro_eventos (solicitacao_id, criado_em DESC);

GRANT SELECT, INSERT ON public.agua_filtro_eventos TO authenticated;
GRANT ALL ON public.agua_filtro_eventos TO service_role;
ALTER TABLE public.agua_filtro_eventos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "agua_filtro_eventos_select" ON public.agua_filtro_eventos
  FOR SELECT TO authenticated USING (public.agua_can('read'));
CREATE POLICY "agua_filtro_eventos_insert" ON public.agua_filtro_eventos
  FOR INSERT TO authenticated WITH CHECK (public.agua_can('update') AND autor = auth.uid());

-- --------------------------------------------------------------------
-- Automação: SLA, próxima troca e trilha
-- --------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.tg_agua_filtro_ativo_proxima()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.atualizado_em := now();
  NEW.proxima_troca := COALESCE(NEW.ultima_troca, NEW.instalado_em) + (NEW.periodicidade_dias || ' days')::interval;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_agua_filtro_ativo_proxima ON public.agua_filtro_ativos;
CREATE TRIGGER trg_agua_filtro_ativo_proxima
  BEFORE INSERT OR UPDATE ON public.agua_filtro_ativos
  FOR EACH ROW EXECUTE FUNCTION public.tg_agua_filtro_ativo_proxima();

CREATE OR REPLACE FUNCTION public.tg_agua_filtro_sla()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  v_horas integer;
BEGIN
  v_horas := CASE NEW.prioridade WHEN 'alta' THEN 24 WHEN 'media' THEN 72 ELSE 168 END;

  IF TG_OP = 'INSERT' OR NEW.prioridade IS DISTINCT FROM OLD.prioridade THEN
    NEW.sla_horas := v_horas;
    NEW.vence_em := COALESCE(NEW.criado_em, now()) + (v_horas || ' hours')::interval;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    NEW.atualizado_em := now();
    IF NEW.situacao = 'concluida' AND OLD.situacao <> 'concluida' THEN
      NEW.concluida_em := COALESCE(NEW.concluida_em, now());
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_agua_filtro_sla ON public.agua_filtro_solicitacoes;
CREATE TRIGGER trg_agua_filtro_sla
  BEFORE INSERT OR UPDATE ON public.agua_filtro_solicitacoes
  FOR EACH ROW EXECUTE FUNCTION public.tg_agua_filtro_sla();

CREATE OR REPLACE FUNCTION public.tg_agua_filtro_trilha()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.agua_filtro_eventos (solicitacao_id, tipo, situacao_nova, comentario, autor)
    VALUES (NEW.id, 'abertura', NEW.situacao, NEW.descricao, NEW.criado_por);
    RETURN NEW;
  END IF;

  IF NEW.situacao IS DISTINCT FROM OLD.situacao THEN
    INSERT INTO public.agua_filtro_eventos (
      solicitacao_id, tipo, situacao_anterior, situacao_nova, comentario, foto_url, autor
    ) VALUES (
      NEW.id,
      CASE NEW.situacao
        WHEN 'em_atendimento' THEN 'execucao'
        WHEN 'concluida' THEN 'conclusao'
        WHEN 'cancelada' THEN 'cancelamento'
        ELSE 'triagem'
      END,
      OLD.situacao,
      NEW.situacao,
      COALESCE(NEW.observacao_conclusao, NEW.motivo_cancelamento),
      NEW.foto_conclusao_url,
      auth.uid()
    );
  END IF;

  -- Conclusão atualiza o ciclo preventivo do ativo
  IF NEW.situacao = 'concluida' AND OLD.situacao <> 'concluida' AND NEW.ativo_id IS NOT NULL THEN
    UPDATE public.agua_filtro_ativos
       SET ultima_troca = COALESCE(NEW.concluida_em::date, CURRENT_DATE)
     WHERE id = NEW.ativo_id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_agua_filtro_trilha ON public.agua_filtro_solicitacoes;
CREATE TRIGGER trg_agua_filtro_trilha
  AFTER INSERT OR UPDATE ON public.agua_filtro_solicitacoes
  FOR EACH ROW EXECUTE FUNCTION public.tg_agua_filtro_trilha();