
ALTER TABLE public.sst_colaboradores
  ADD COLUMN IF NOT EXISTS regional text,
  ADD COLUMN IF NOT EXISTS descricao_filial text,
  ADD COLUMN IF NOT EXISTS gerente text,
  ADD COLUMN IF NOT EXISTS gerente_regional text,
  ADD COLUMN IF NOT EXISTS diretor text,
  ADD COLUMN IF NOT EXISTS diretor_executivo text,
  ADD COLUMN IF NOT EXISTS negocio text,
  ADD COLUMN IF NOT EXISTS cod_funcao text,
  ADD COLUMN IF NOT EXISTS descricao_funcao text,
  ADD COLUMN IF NOT EXISTS escala text,
  ADD COLUMN IF NOT EXISTS sexo text,
  ADD COLUMN IF NOT EXISTS rg text,
  ADD COLUMN IF NOT EXISTS data_nascimento date,
  ADD COLUMN IF NOT EXISTS municipio text,
  ADD COLUMN IF NOT EXISTS estado text,
  ADD COLUMN IF NOT EXISTS pis text,
  ADD COLUMN IF NOT EXISTS ctps text,
  ADD COLUMN IF NOT EXISTS serie_ctps text,
  ADD COLUMN IF NOT EXISTS horario_trabalho text,
  ADD COLUMN IF NOT EXISTS cc text,
  ADD COLUMN IF NOT EXISTS cr text,
  ADD COLUMN IF NOT EXISTS tipo_contrato text,
  ADD COLUMN IF NOT EXISTS data_demissao date,
  ADD COLUMN IF NOT EXISTS dados_extras jsonb NOT NULL DEFAULT '{}'::jsonb;
